- name: Ensures nginx's repo key is present
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Ensures required PPAs are present
  apt_repository: repo='$item' update_cache=yes
  with_items:
    - 'ppa:ondrej/php5'
    - 'deb http://nginx.org/packages/ubuntu/ precise nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ precise nginx'

- name: Ensures required packages are installed
  apt: pkg='$item' state=present
  with_items:
    - php5
    - php5-dev
    - php-pear
    - php5-fpm
    - php5-cli
    - php5-intl
    - php5-mysql
    - nginx

- name: Ensure php-fpm log directory exists
  file: path=/var/log/php-fpm state=directory

- name: Ensure nginx sites* dirs are present
  file: path=/etc/nginx/$item state=directory
  with_items:
    - 'sites-available'
    - 'sites-enabled'

- name: Ensure default nginx conf.d directory is deleted
  file: path=/etc/nginx/conf.d state=absent

- name: Ensure nginx configuration file is at the latest version.
  copy: src='$item' dest=/etc/nginx/
  with_items:
    - nginx.conf
    - fastcgi_params
  notify:
    - check nginx conf
    - reload nginx

- name: Ensure nginx vhosts are at the latest version.
  template: src='$item' dest=/etc/nginx/sites-enabled/
  with_fileglob:
    - ../templates/sites-enabled/*
  notify:
    - check nginx conf
    - reload nginx

- name: Ensure ngnx is started
  service: name=nginx state=started

- name: Ensure php-fpm is restarted
  service: name=php5-fpm state=restarted

- name: Ensure php-fpm pools are at the latest version.
  template: src='$item' dest=/etc/php5/fpm/pool.d/
  with_fileglob:
    - ../templates/php/fpm.d/*
  notify:
    - restart php-fpm

- name: Ensure php-fpm pools are at the latest version.
  template: src=php/php.ini dest=/etc/php5/ owner=root group=root
  notify:
    - restart php-fpm

- name: Ensure there's only a php.ini not that fragmented bullshit ubuntu comes with
  file:
    src=/etc/php5/php.ini
    dest=/etc/php5/$item/php.ini
    owner=root group=root state=link
    force=yes
  with_items:
   - fpm
   - cli

- name: Ensure mysql and mysqli are disabled
  file: path='$item' state=absent
  with_items:
    - /etc/php5/fpm/conf.d/20-mysqli.ini
    - /etc/php5/fpm/conf.d/20-mysql.ini
    - /etc/php5/cli/conf.d/20-mysqli.ini
    - /etc/php5/cli/conf.d/20-mysql.ini
  notify:
    - restart php-fpm

- name: Ensure opcache config is correct
  template: src=php/mods-available/opcache.ini.j2 dest=/etc/php5/mods-available/opcache.ini
  notify:
    - restart php-fpm

- name: Ensure composer is installed
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin && mv /usr/bin/composer.phar /usr/bin/composer creates=/usr/bin/composer

# PEAR Packages
# ####################
- name: PHP | PHPDev | Update pear packages
  command: pear upgrade

- name: PHP | PHPDev | Set pear auto-discover
  command: pear config-set auto_discover 1

- name: PHP | PHPDev | Pear install the PHP QA Toolchain
  command: pear install pear.phpqatools.org/phpqatools creates=/usr/bin/phpunit
  # this fails often (dns problems, pear problems, etc. So just ignore the errors and continue.)
  ignore_errors: True

# PECL Packages
# #####################

- include: pecl.yml package=redis version=stable stdin=
