- hosts: all
  user: vagrant
  sudo: yes

  tasks:

    - name: Updates apt cache
      apt: update_cache=yes

    - name: Ensures all system packages are at the latest version
      apt: upgrade=dist

    - name: Ensures snake user is present
      user: name=snake generate_ssh_key=yes

    - name: Ensures python-software-properties (add-apt-repository) is installed
      apt: pkg=python-software-properties state=latest

    - name: Ensures Percona apt-key is present
      apt_key: url=http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona state=present

    - name: Ensures required PPAs are present
      apt_repository: repo='{{ item }}' update_cache=yes
      with_items:
        - 'ppa:ondrej/php5'
        - 'ppa:nginx/stable'
        - 'ppa:rwky/redis'
        - 'deb http://repo.percona.com/apt precise main'
        - 'deb-src http://repo.percona.com/apt precise main'

    - name: Ensures required packages are installed
      apt: pkg={{ item }} state=present
      with_items:
        - ntp
        - php5
        - php5-fpm
        - php5-cli
        - nginx
        - redis-server
        - percona-server-server-5.1

    - name: Ensures nginx configuration file is at the latest version.
      copy: src=files/conf/nginx/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - reload nginx
        - start nginx

    - name: Ensures nginx vhosts are at the latest version.
      copy: src={{ item }} dest=/etc/nginx/sites-enabled/
      with_fileglob:
        - files/conf/nginx/sites-enabled/*
      notify:
        - reload nginx
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started

    - name: reload nginx
      service: name=nginx state=reloaded