- name: check nginx conf
  command: nginx -t

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload php-fpm # NON FUNZIONA PERCHE' IL MAINTAINER DELLA PPA E' BRAVO
  service: name=php5-fpm state=reloaded

- name: restart php-fpm
  service: name=php5-fpm state=restarted
