- name: check nginx conf
  command: nginx -t

- name: reload nginx
  service: name=nginx state=reloaded

- name: reload php-fpm
  service: name=php5-fpm state=reloaded

- name: restart php-fpm
  service: name=php5-fpm state=restarted
